# Staging Environment Configuration
stage: staging
region: us-east-1

# Environment Variables for AWS deployment
# These are placeholders - actual values will be CloudFormation refs
environment:
  TASK_QUEUE_URL: !Ref TaskQueue
  DLQ_URL: !Ref TaskDLQ

# Lambda Configuration
lambda:
  timeout: 300
  memorySize: 1024
  runtime: nodejs18.x

# SQS Configuration
sqs:
  visibilityTimeoutSeconds: 300
  messageRetentionPeriod: 1209600  # 14 days
  maxReceiveCount: 3  # Initial + 2 retries
  batchSize: 5

# DynamoDB Configuration
dynamodb:
  billingMode: PAY_PER_REQUEST
  pointInTimeRecovery: true
  streamViewType: NEW_AND_OLD_IMAGES

# API Gateway Configuration
apiGateway:
  cors: true
  requestValidation: true

# Monitoring Configuration
monitoring:
  enableXRay: true
  logRetention: 14  # days

# Task Processing Configuration
taskProcessing:
  maxRetries: 2
  baseDelaySeconds: 2
  maxDelaySeconds: 900  # 15 minutes
  failureRate: 0.3  # 30% failure simulation (back to normal)

# Tags
tags:
  Environment: staging
  Project: learn-dlq
  Owner: team