# Development Environment Configuration
stage: dev
region: us-east-1

# Lambda Configuration
lambda:
  timeout: 30
  memorySize: 256

# SQS Configuration
sqs:
  batchSize: 10
  visibilityTimeout: 900  # 15 minutes
  messageRetentionPeriod: 1209600  # 14 days
  maxRetries: 2

# DynamoDB Configuration
dynamodb:
  billingMode: PAY_PER_REQUEST
  pointInTimeRecovery: false
  deletionProtection: false

# Environment Variables
environment:
  STAGE: dev
  LOG_LEVEL: debug
  FAILURE_RATE: 0.3

# API Gateway Configuration
apiGateway:
  cors: true
  requestValidation: false

# Monitoring Configuration
monitoring:
  enableXRay: false
  logRetention: 7  # days

# Task Processing Configuration
taskProcessing:
  maxRetries: 2
  baseDelaySeconds: 2
  maxDelaySeconds: 900  # 15 minutes
  failureRate: 0.3  # 30% failure simulation

# CloudFormation Tags
tags:
  Environment: dev
  Project: learn-dlq
  Owner: developer