# Local Development Environment Configuration
stage: local
region: us-east-1

# Environment Variables for LocalStack
environment:
  TASK_QUEUE_URL: http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/learn-dlq-task-queue-local
  DLQ_URL: http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/learn-dlq-task-dlq-local

# Lambda Configuration
lambda:
  timeout: 300
  memorySize: 512
  runtime: nodejs18.x

# SQS Configuration
sqs:
  visibilityTimeoutSeconds: 300
  messageRetentionPeriod: 1209600  # 14 days
  maxReceiveCount: 3  # Initial + 2 retries
  batchSize: 1

# DynamoDB Configuration
dynamodb:
  billingMode: PAY_PER_REQUEST
  pointInTimeRecovery: false
  streamViewType: NEW_AND_OLD_IMAGES

# API Gateway Configuration
apiGateway:
  cors: true
  requestValidation: false

# Monitoring Configuration
monitoring:
  enableXRay: false
  logRetention: 7  # days

# Task Processing Configuration
taskProcessing:
  maxRetries: 2
  baseDelaySeconds: 2
  maxDelaySeconds: 900  # 15 minutes
  failureRate: 0.3  # 30% failure simulation for testing

# Tags
tags:
  Environment: local
  Project: learn-dlq
  Owner: developer 