# Staging Environment Configuration
stage: staging
region: us-east-1

# Lambda Configuration
lambda:
  timeout: 300
  memorySize: 1024
  runtime: nodejs18.x

# SQS Configuration
sqs:
  visibilityTimeoutSeconds: 300
  messageRetentionPeriod: 1209600  # 14 days
  maxReceiveCount: 3  # Initial + 2 retries
  batchSize: 5

# DynamoDB Configuration
dynamodb:
  billingMode: PAY_PER_REQUEST
  pointInTimeRecovery: true
  streamViewType: NEW_AND_OLD_IMAGES

# API Gateway Configuration
apiGateway:
  cors: true
  requestValidation: true

# Monitoring Configuration
monitoring:
  enableXRay: true
  logRetention: 14  # days

# Task Processing Configuration
taskProcessing:
  maxRetries: 2
  baseDelaySeconds: 2
  maxDelaySeconds: 900  # 15 minutes
  failureRate: 0.2  # 20% failure simulation

# Tags
tags:
  Environment: staging
  Project: learn-dlq
  Owner: team